# Generated by Django 4.0.4 on 2022-08-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifest_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestmodel',
            name='image_url',
            field=models.URLField(default='https://images.unsplash.com/photo-1609517269751-3c8de889ce97?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80'),
        ),
    ]
